name : Docker-CI
trigger: none

resources:
 pipelines:
   - pipeline: CI
     source: TablesCI
     trigger: true
pool:
  vmImage: 'ubuntu-latest'

 
stages:
- stage: Deploy
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build and push Docker image
    steps:
    - task: Docker@2
      displayName: 'Build the Docker image'
      inputs:
        containerRegistry: 'Docker Hub'
        command: 'buildAndPush'
        dockerFile: '**/Dockerfile'
        repository: 'olegiys/tablesapi'
        buildContext: '.'
        
       
