name : Docker-CI
trigger:
  branches:
    include:
      - master
 
pool:
  vmImage: 'ubuntu-latest'

 
stages:
- stage: BuildSolution 
  displayName: Build
  jobs:
    - job: Build
      displayName: BuildProject
      steps:
       - task: NuGetCommand@2
         inputs:
            command: 'restore'
            restoreSolution: '**/*.sln'
            feedsToUse: 'select'
       - task: VSBuild@1
         inputs:
           solution: '**\*.sln'
- stage: Deploy
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build and push Docker image
    steps:
    - task: Docker@2
      displayName: 'Build the Docker image'
      inputs:
        containerRegistry: 'Docker Hub'
        command: 'buildAndPush'
        dockerFile: '**/Dockerfile'
        repository: 'olegiys/tablesapi'
        buildContext: '.'
        
       
